<%@ page contentType="text/html; charset=utf-8" language="java"%>
<%@ page
	import="java.sql.*, javax.sql.*, java.net.*, java.io.*,java.util.*"%>
<html>
<head>
<title>makedata.jsp</title>
</head>
<body>
	<h1>Make table</h1>

	<%
	Class.forName("com.mysql.cj.jdbc.Driver"); // JDBC 드라이버를 로드
	Connection conn = DriverManager.getConnection("jdbc:mysql://192.168.23.200:33060/kopo33", "root", "choi0924"); // 데이터베이스에 연결
	Statement stmt = conn.createStatement(); // SQL 문 실행을 위한 Statement 객체를 실행
	%>

	<%
	try {
		stmt.execute("drop table if exists stock");
		out.println("drop table stock OK<br>");
	} catch (Exception e) {
		out.println("drop table stock NOT OK<br>");
		out.println(e.toString());
	}
	%>
	<%
	stmt.execute(
			"create table stock(id int auto_increment not null primary key , title varchar(50), amount int, createdate Date, date Date, content text, img text) DEFAULT CHARSET=UTF8");
	%>
	<%
	String sql = "";
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('바나나','6', NOW(), NOW(), '바나나')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('딸기','5', NOW(), NOW(), '딸기')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('포도','4', NOW(), NOW(), '포도')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('망고','10', NOW(), NOW(), '망고')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('오렌지','2', NOW(), NOW(), '오렌지')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('한라봉','1', NOW(), NOW(), '한라봉')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('바나나','6', NOW(), NOW(), '바나나')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('딸기','5', NOW(), NOW(), '딸기')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('포도','4', NOW(), NOW(), '포도')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('망고','10', NOW(), NOW(), '망고')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('오렌지','2', NOW(), NOW(), '오렌지')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('한라봉','1', NOW(), NOW(), '한라봉')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('바나나','6', NOW(), NOW(), '바나나')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('딸기','5', NOW(), NOW(), '딸기')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('포도','4', NOW(), NOW(), '포도')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('망고','10', NOW(), NOW(), '망고')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('오렌지','2', NOW(), NOW(), '오렌지')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('한라봉','1', NOW(), NOW(), '한라봉')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('바나나','6', NOW(), NOW(), '바나나')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('딸기','5', NOW(), NOW(), '딸기')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('포도','4', NOW(), NOW(), '포도')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('망고','10', NOW(), NOW(), '망고')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('오렌지','2', NOW(), NOW(), '오렌지')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('한라봉','1', NOW(), NOW(), '한라봉')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('바나나','6', NOW(), NOW(), '바나나')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('딸기','5', NOW(), NOW(), '딸기')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('포도','4', NOW(), NOW(), '포도')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('망고','10', NOW(), NOW(), '망고')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('오렌지','2', NOW(), NOW(), '오렌지')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('한라봉','1', NOW(), NOW(), '한라봉')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('바나나','6', NOW(), NOW(), '바나나')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('딸기','5', NOW(), NOW(), '딸기')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('포도','4', NOW(), NOW(), '포도')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('망고','10', NOW(), NOW(), '망고')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('오렌지','2', NOW(), NOW(), '오렌지')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('한라봉','1', NOW(), NOW(), '한라봉')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('바나나','6', NOW(), NOW(), '바나나')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('딸기','5', NOW(), NOW(), '딸기')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('포도','4', NOW(), NOW(), '포도')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('망고','10', NOW(), NOW(), '망고')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('오렌지','2', NOW(), NOW(), '오렌지')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('한라봉','1', NOW(), NOW(), '한라봉')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('바나나','6', NOW(), NOW(), '바나나')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('딸기','5', NOW(), NOW(), '딸기')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('포도','4', NOW(), NOW(), '포도')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('망고','10', NOW(), NOW(), '망고')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('오렌지','2', NOW(), NOW(), '오렌지')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('한라봉','1', NOW(), NOW(), '한라봉')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('바나나','6', NOW(), NOW(), '바나나')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('딸기','5', NOW(), NOW(), '딸기')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('포도','4', NOW(), NOW(), '포도')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('망고','10', NOW(), NOW(), '망고')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('오렌지','2', NOW(), NOW(), '오렌지')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('한라봉','1', NOW(), NOW(), '한라봉')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('바나나','6', NOW(), NOW(), '바나나')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('딸기','5', NOW(), NOW(), '딸기')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('포도','4', NOW(), NOW(), '포도')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('망고','10', NOW(), NOW(), '망고')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('오렌지','2', NOW(), NOW(), '오렌지')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('한라봉','1', NOW(), NOW(), '한라봉')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('바나나','6', NOW(), NOW(), '바나나')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('딸기','5', NOW(), NOW(), '딸기')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('포도','4', NOW(), NOW(), '포도')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('망고','10', NOW(), NOW(), '망고')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('오렌지','2', NOW(), NOW(), '오렌지')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('한라봉','1', NOW(), NOW(), '한라봉')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('바나나','6', NOW(), NOW(), '바나나')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('딸기','5', NOW(), NOW(), '딸기')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('포도','4', NOW(), NOW(), '포도')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('망고','10', NOW(), NOW(), '망고')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('오렌지','2', NOW(), NOW(), '오렌지')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('한라봉','1', NOW(), NOW(), '한라봉')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('바나나','6', NOW(), NOW(), '바나나')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('딸기','5', NOW(), NOW(), '딸기')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('포도','4', NOW(), NOW(), '포도')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('망고','10', NOW(), NOW(), '망고')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('오렌지','2', NOW(), NOW(), '오렌지')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('한라봉','1', NOW(), NOW(), '한라봉')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('바나나','6', NOW(), NOW(), '바나나')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('딸기','5', NOW(), NOW(), '딸기')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('포도','4', NOW(), NOW(), '포도')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('망고','10', NOW(), NOW(), '망고')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('오렌지','2', NOW(), NOW(), '오렌지')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('한라봉','1', NOW(), NOW(), '한라봉')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('바나나','6', NOW(), NOW(), '바나나')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('딸기','5', NOW(), NOW(), '딸기')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('포도','4', NOW(), NOW(), '포도')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('망고','10', NOW(), NOW(), '망고')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('오렌지','2', NOW(), NOW(), '오렌지')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('한라봉','1', NOW(), NOW(), '한라봉')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('바나나','6', NOW(), NOW(), '바나나')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('딸기','5', NOW(), NOW(), '딸기')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('포도','4', NOW(), NOW(), '포도')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('망고','10', NOW(), NOW(), '망고')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('오렌지','2', NOW(), NOW(), '오렌지')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('한라봉','1', NOW(), NOW(), '한라봉')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('바나나','6', NOW(), NOW(), '바나나')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('딸기','5', NOW(), NOW(), '딸기')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('포도','4', NOW(), NOW(), '포도')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('망고','10', NOW(), NOW(), '망고')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('오렌지','2', NOW(), NOW(), '오렌지')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('한라봉','1', NOW(), NOW(), '한라봉')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('바나나','6', NOW(), NOW(), '바나나')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('딸기','5', NOW(), NOW(), '딸기')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('포도','4', NOW(), NOW(), '포도')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('망고','10', NOW(), NOW(), '망고')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('오렌지','2', NOW(), NOW(), '오렌지')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('한라봉','1', NOW(), NOW(), '한라봉')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('바나나','6', NOW(), NOW(), '바나나')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('딸기','5', NOW(), NOW(), '딸기')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('포도','4', NOW(), NOW(), '포도')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('망고','10', NOW(), NOW(), '망고')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('오렌지','2', NOW(), NOW(), '오렌지')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('한라봉','1', NOW(), NOW(), '한라봉')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('바나나','6', NOW(), NOW(), '바나나')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('딸기','5', NOW(), NOW(), '딸기')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('포도','4', NOW(), NOW(), '포도')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('망고','10', NOW(), NOW(), '망고')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('오렌지','2', NOW(), NOW(), '오렌지')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('한라봉','1', NOW(), NOW(), '한라봉')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('바나나','6', NOW(), NOW(), '바나나')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('딸기','5', NOW(), NOW(), '딸기')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('포도','4', NOW(), NOW(), '포도')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('망고','10', NOW(), NOW(), '망고')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('오렌지','2', NOW(), NOW(), '오렌지')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('한라봉','1', NOW(), NOW(), '한라봉')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('바나나','6', NOW(), NOW(), '바나나')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('딸기','5', NOW(), NOW(), '딸기')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('포도','4', NOW(), NOW(), '포도')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('망고','10', NOW(), NOW(), '망고')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('오렌지','2', NOW(), NOW(), '오렌지')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('한라봉','1', NOW(), NOW(), '한라봉')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('바나나','6', NOW(), NOW(), '바나나')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('딸기','5', NOW(), NOW(), '딸기')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('포도','4', NOW(), NOW(), '포도')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('망고','10', NOW(), NOW(), '망고')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('오렌지','2', NOW(), NOW(), '오렌지')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('한라봉','1', NOW(), NOW(), '한라봉')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('바나나','6', NOW(), NOW(), '바나나')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('딸기','5', NOW(), NOW(), '딸기')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('포도','4', NOW(), NOW(), '포도')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('망고','10', NOW(), NOW(), '망고')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('오렌지','2', NOW(), NOW(), '오렌지')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('한라봉','1', NOW(), NOW(), '한라봉')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('바나나','6', NOW(), NOW(), '바나나')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('딸기','5', NOW(), NOW(), '딸기')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('포도','4', NOW(), NOW(), '포도')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('망고','10', NOW(), NOW(), '망고')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('오렌지','2', NOW(), NOW(), '오렌지')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('한라봉','1', NOW(), NOW(), '한라봉')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('바나나','6', NOW(), NOW(), '바나나')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('딸기','5', NOW(), NOW(), '딸기')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('포도','4', NOW(), NOW(), '포도')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('망고','10', NOW(), NOW(), '망고')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('오렌지','2', NOW(), NOW(), '오렌지')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('한라봉','1', NOW(), NOW(), '한라봉')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('바나나','6', NOW(), NOW(), '바나나')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('딸기','5', NOW(), NOW(), '딸기')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('포도','4', NOW(), NOW(), '포도')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('망고','10', NOW(), NOW(), '망고')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('오렌지','2', NOW(), NOW(), '오렌지')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('한라봉','1', NOW(), NOW(), '한라봉')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('바나나','6', NOW(), NOW(), '바나나')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('딸기','5', NOW(), NOW(), '딸기')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('포도','4', NOW(), NOW(), '포도')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('망고','10', NOW(), NOW(), '망고')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('오렌지','2', NOW(), NOW(), '오렌지')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('한라봉','1', NOW(), NOW(), '한라봉')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('바나나','6', NOW(), NOW(), '바나나')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('딸기','5', NOW(), NOW(), '딸기')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('포도','4', NOW(), NOW(), '포도')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('망고','10', NOW(), NOW(), '망고')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('오렌지','2', NOW(), NOW(), '오렌지')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('한라봉','1', NOW(), NOW(), '한라봉')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('바나나','6', NOW(), NOW(), '바나나')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('딸기','5', NOW(), NOW(), '딸기')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('포도','4', NOW(), NOW(), '포도')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('망고','10', NOW(), NOW(), '망고')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('오렌지','2', NOW(), NOW(), '오렌지')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('한라봉','1', NOW(), NOW(), '한라봉')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('바나나','6', NOW(), NOW(), '바나나')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('딸기','5', NOW(), NOW(), '딸기')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('포도','4', NOW(), NOW(), '포도')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('망고','10', NOW(), NOW(), '망고')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('오렌지','2', NOW(), NOW(), '오렌지')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('한라봉','1', NOW(), NOW(), '한라봉')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('바나나','6', NOW(), NOW(), '바나나')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('딸기','5', NOW(), NOW(), '딸기')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('포도','4', NOW(), NOW(), '포도')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('망고','10', NOW(), NOW(), '망고')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('오렌지','2', NOW(), NOW(), '오렌지')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('한라봉','1', NOW(), NOW(), '한라봉')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('바나나','6', NOW(), NOW(), '바나나')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('딸기','5', NOW(), NOW(), '딸기')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('포도','4', NOW(), NOW(), '포도')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('망고','10', NOW(), NOW(), '망고')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('오렌지','2', NOW(), NOW(), '오렌지')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('한라봉','1', NOW(), NOW(), '한라봉')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('바나나','6', NOW(), NOW(), '바나나')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('딸기','5', NOW(), NOW(), '딸기')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('포도','4', NOW(), NOW(), '포도')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('망고','10', NOW(), NOW(), '망고')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('오렌지','2', NOW(), NOW(), '오렌지')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('한라봉','1', NOW(), NOW(), '한라봉')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('바나나','6', NOW(), NOW(), '바나나')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('딸기','5', NOW(), NOW(), '딸기')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('포도','4', NOW(), NOW(), '포도')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('망고','10', NOW(), NOW(), '망고')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('오렌지','2', NOW(), NOW(), '오렌지')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('한라봉','1', NOW(), NOW(), '한라봉')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('바나나','6', NOW(), NOW(), '바나나')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('딸기','5', NOW(), NOW(), '딸기')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('포도','4', NOW(), NOW(), '포도')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('망고','10', NOW(), NOW(), '망고')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('오렌지','2', NOW(), NOW(), '오렌지')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('한라봉','1', NOW(), NOW(), '한라봉')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('바나나','6', NOW(), NOW(), '바나나')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('딸기','5', NOW(), NOW(), '딸기')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('포도','4', NOW(), NOW(), '포도')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('망고','10', NOW(), NOW(), '망고')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('오렌지','2', NOW(), NOW(), '오렌지')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('한라봉','1', NOW(), NOW(), '한라봉')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('바나나','6', NOW(), NOW(), '바나나')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('딸기','5', NOW(), NOW(), '딸기')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('포도','4', NOW(), NOW(), '포도')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('망고','10', NOW(), NOW(), '망고')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('오렌지','2', NOW(), NOW(), '오렌지')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('한라봉','1', NOW(), NOW(), '한라봉')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('바나나','6', NOW(), NOW(), '바나나')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('딸기','5', NOW(), NOW(), '딸기')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('포도','4', NOW(), NOW(), '포도')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('망고','10', NOW(), NOW(), '망고')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('오렌지','2', NOW(), NOW(), '오렌지')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('한라봉','1', NOW(), NOW(), '한라봉')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('바나나','6', NOW(), NOW(), '바나나')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('딸기','5', NOW(), NOW(), '딸기')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('포도','4', NOW(), NOW(), '포도')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('망고','10', NOW(), NOW(), '망고')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('오렌지','2', NOW(), NOW(), '오렌지')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('한라봉','1', NOW(), NOW(), '한라봉')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('바나나','6', NOW(), NOW(), '바나나')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('딸기','5', NOW(), NOW(), '딸기')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('포도','4', NOW(), NOW(), '포도')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('망고','10', NOW(), NOW(), '망고')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('오렌지','2', NOW(), NOW(), '오렌지')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('한라봉','1', NOW(), NOW(), '한라봉')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('바나나','6', NOW(), NOW(), '바나나')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('딸기','5', NOW(), NOW(), '딸기')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('포도','4', NOW(), NOW(), '포도')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('망고','10', NOW(), NOW(), '망고')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('오렌지','2', NOW(), NOW(), '오렌지')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('한라봉','1', NOW(), NOW(), '한라봉')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('바나나','6', NOW(), NOW(), '바나나')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('딸기','5', NOW(), NOW(), '딸기')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('포도','4', NOW(), NOW(), '포도')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('망고','10', NOW(), NOW(), '망고')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('오렌지','2', NOW(), NOW(), '오렌지')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('한라봉','1', NOW(), NOW(), '한라봉')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('바나나','6', NOW(), NOW(), '바나나')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('딸기','5', NOW(), NOW(), '딸기')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('포도','4', NOW(), NOW(), '포도')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('망고','10', NOW(), NOW(), '망고')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('오렌지','2', NOW(), NOW(), '오렌지')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('한라봉','1', NOW(), NOW(), '한라봉')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('바나나','6', NOW(), NOW(), '바나나')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('딸기','5', NOW(), NOW(), '딸기')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('포도','4', NOW(), NOW(), '포도')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('망고','10', NOW(), NOW(), '망고')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('오렌지','2', NOW(), NOW(), '오렌지')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('한라봉','1', NOW(), NOW(), '한라봉')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('바나나','6', NOW(), NOW(), '바나나')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('딸기','5', NOW(), NOW(), '딸기')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('포도','4', NOW(), NOW(), '포도')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('망고','10', NOW(), NOW(), '망고')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('오렌지','2', NOW(), NOW(), '오렌지')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('한라봉','1', NOW(), NOW(), '한라봉')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('바나나','6', NOW(), NOW(), '바나나')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('딸기','5', NOW(), NOW(), '딸기')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('포도','4', NOW(), NOW(), '포도')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('망고','10', NOW(), NOW(), '망고')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('오렌지','2', NOW(), NOW(), '오렌지')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('한라봉','1', NOW(), NOW(), '한라봉')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('바나나','6', NOW(), NOW(), '바나나')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('딸기','5', NOW(), NOW(), '딸기')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('포도','4', NOW(), NOW(), '포도')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('망고','10', NOW(), NOW(), '망고')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('오렌지','2', NOW(), NOW(), '오렌지')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('한라봉','1', NOW(), NOW(), '한라봉')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('바나나','6', NOW(), NOW(), '바나나')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('딸기','5', NOW(), NOW(), '딸기')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('포도','4', NOW(), NOW(), '포도')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('망고','10', NOW(), NOW(), '망고')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('오렌지','2', NOW(), NOW(), '오렌지')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('한라봉','1', NOW(), NOW(), '한라봉')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('바나나','6', NOW(), NOW(), '바나나')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('딸기','5', NOW(), NOW(), '딸기')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('포도','4', NOW(), NOW(), '포도')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('망고','10', NOW(), NOW(), '망고')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('오렌지','2', NOW(), NOW(), '오렌지')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('한라봉','1', NOW(), NOW(), '한라봉')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('바나나','6', NOW(), NOW(), '바나나')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('딸기','5', NOW(), NOW(), '딸기')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('포도','4', NOW(), NOW(), '포도')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('망고','10', NOW(), NOW(), '망고')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('오렌지','2', NOW(), NOW(), '오렌지')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('한라봉','1', NOW(), NOW(), '한라봉')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('바나나','6', NOW(), NOW(), '바나나')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('딸기','5', NOW(), NOW(), '딸기')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('포도','4', NOW(), NOW(), '포도')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('망고','10', NOW(), NOW(), '망고')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('오렌지','2', NOW(), NOW(), '오렌지')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('한라봉','1', NOW(), NOW(), '한라봉')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('바나나','6', NOW(), NOW(), '바나나')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('딸기','5', NOW(), NOW(), '딸기')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('포도','4', NOW(), NOW(), '포도')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('망고','10', NOW(), NOW(), '망고')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('오렌지','2', NOW(), NOW(), '오렌지')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('한라봉','1', NOW(), NOW(), '한라봉')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('바나나','6', NOW(), NOW(), '바나나')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('딸기','5', NOW(), NOW(), '딸기')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('포도','4', NOW(), NOW(), '포도')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('망고','10', NOW(), NOW(), '망고')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('오렌지','2', NOW(), NOW(), '오렌지')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('한라봉','1', NOW(), NOW(), '한라봉')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('바나나','6', NOW(), NOW(), '바나나')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('딸기','5', NOW(), NOW(), '딸기')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('포도','4', NOW(), NOW(), '포도')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('망고','10', NOW(), NOW(), '망고')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('오렌지','2', NOW(), NOW(), '오렌지')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('한라봉','1', NOW(), NOW(), '한라봉')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('바나나','6', NOW(), NOW(), '바나나')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('딸기','5', NOW(), NOW(), '딸기')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('포도','4', NOW(), NOW(), '포도')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('망고','10', NOW(), NOW(), '망고')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('오렌지','2', NOW(), NOW(), '오렌지')";
	stmt.execute(sql);
	sql = "INSERT INTO stock(title, amount, createdate, date, content) values('한라봉','1', NOW(), NOW(), '한라봉')";
	stmt.execute(sql);
	

	stmt.close(); // Statement 객체 닫기
	conn.close(); // Connection 객체 닫기
	%>

</body>
</html>